[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "orz"
version = "0.1.0"
description = "Open-Reasoner-Zero"
authors = [
    {name = "Open-Reasoner-Zero team", email = "hanqer@stepfun.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "black==22.8.0",
    "joblib",
    "tabulate",
    "tensorboardX",
    "tqdm",
    "sentencepiece",
    "pytest",
    "pytest-cov",
    "loguru",
    "omegaconf",
    "numpy",
    "ray[default]==2.40.0",
    "torch==2.5.1",
    "torchaudio==2.5.1",
    "torchvision==0.20.1",
    "vllm==0.6.5",
    "xformers",
    "tensorboard",
    "hydra-core",
    "charset-normalizer",
    "jinja2",
    "flash-attn",
    "deepspeed==0.16.0",
    "pydantic",
    "chardet",
    "peft",
    "transformers",
    "accelerate",
    "typing-extensions",
    "annotated-types",
    "aiosignal",
    "aiohttp",
    "asyncio",
    "multidict",
    "yarl",
    "frozenlist",
    "async-timeout",
    "attrs",
    "idna",
    "antlr4-python3-runtime==4.9.3",
    "PyYAML",
    "packaging>=25.0",
    "msgpack>=1.1.1",
]

[project.optional-dependencies]
dev = [
    "pytest>=6.2.5"
]

[tool.setuptools]
packages = ["orz",]

[tool.setuptools.dynamic]
version = {attr = "orz.__version__"}
readme = {file = ["README.md"]}

[tool.pytest.ini_options]
addopts = "-v -s"
testpaths = [
    "tests",
]

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 120
known_third_party = "wandb"

[tool.black]
line-length = 120
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/
'''

[tool.flake8]
max-line-length = 120
max-doc-length = 120
extend-ignore = [
    # Default ignored errors by flake8
    "E121", "E123", "E126", "E226", "E24", "E704",
    # F401 module imported but unused
    "F401",
    # E203 whitespace before ':' (conflict with black)
    "E203",
    # E231 missing whitespace after ',' (conflict with black)
    "E231",
    # E501 line too long (conflict with black)
    "E501",
    # E741 do not use variables named 'l', 'O', or 'I'
    "E741",
    # W503 line break before binary operator (conflict with black)
    "W503",
    # W504 line break after binary operator (conflict with black)
    "W504",
    # W505 doc line too long (conflict with black)
    "W505",
    # W605 invalid escape sequence 'x' (conflict with latex within docs)
    "W605",
]
